name: A-Team Common
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test-firmware-build:
    runs-on: [ubuntu-20.04, ubuntu-22.04, macos-latest]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config:
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Validate Nix Envoirnment
        shell: bash
        run: |
          nix flake check
          nix develop -c cargo --version
      - name: Build Common Items
        shell: bash
        run: |
          nix develop -c make bindgen-packets
      - name: Test Common Items
        shell: bash
        run: |
          nix develop -c make bindgen-packets-test

